# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from myprotobuf import Demo_pb2 as myprotobuf_dot_Demo__pb2


class GrpcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getDifference = channel.unary_unary(
                '/GrpcService/getDifference',
                request_serializer=myprotobuf_dot_Demo__pb2.DifferenceRequest.SerializeToString,
                response_deserializer=myprotobuf_dot_Demo__pb2.DifferenceResponse.FromString,
                )
        self.GetRecommendJob = channel.unary_unary(
                '/GrpcService/GetRecommendJob',
                request_serializer=myprotobuf_dot_Demo__pb2.GetRecommendJobRequest.SerializeToString,
                response_deserializer=myprotobuf_dot_Demo__pb2.GetRecommendJobResponse.FromString,
                )
        self.ExtractResume = channel.unary_unary(
                '/GrpcService/ExtractResume',
                request_serializer=myprotobuf_dot_Demo__pb2.ExtractResumeRequest.SerializeToString,
                response_deserializer=myprotobuf_dot_Demo__pb2.ExtractResumeResponse.FromString,
                )


class GrpcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getDifference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecommendJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractResume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getDifference': grpc.unary_unary_rpc_method_handler(
                    servicer.getDifference,
                    request_deserializer=myprotobuf_dot_Demo__pb2.DifferenceRequest.FromString,
                    response_serializer=myprotobuf_dot_Demo__pb2.DifferenceResponse.SerializeToString,
            ),
            'GetRecommendJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecommendJob,
                    request_deserializer=myprotobuf_dot_Demo__pb2.GetRecommendJobRequest.FromString,
                    response_serializer=myprotobuf_dot_Demo__pb2.GetRecommendJobResponse.SerializeToString,
            ),
            'ExtractResume': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractResume,
                    request_deserializer=myprotobuf_dot_Demo__pb2.ExtractResumeRequest.FromString,
                    response_serializer=myprotobuf_dot_Demo__pb2.ExtractResumeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GrpcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getDifference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GrpcService/getDifference',
            myprotobuf_dot_Demo__pb2.DifferenceRequest.SerializeToString,
            myprotobuf_dot_Demo__pb2.DifferenceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRecommendJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GrpcService/GetRecommendJob',
            myprotobuf_dot_Demo__pb2.GetRecommendJobRequest.SerializeToString,
            myprotobuf_dot_Demo__pb2.GetRecommendJobResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExtractResume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GrpcService/ExtractResume',
            myprotobuf_dot_Demo__pb2.ExtractResumeRequest.SerializeToString,
            myprotobuf_dot_Demo__pb2.ExtractResumeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
